### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by einsteinsci** [einsteinsci/BetterBeginningsReborn#1]
Update to 1.12. Get it working and running correctly.

Then add and rework stuff.

**Comment by Daomephsta** [comment]
Update checklist:
- [x] Fix compile errors
- [x] Lowercase all resource names
- [x] Port item, block, entity and model registries to the new registry event system
- [x] Get BB to a state where worlds are loadable
- [ ] Fix itemstack sentinel issues.
- [ ] Reimplement achievements as advancements
- [ ] Convert BB's vanilla crafting recipes to .json format
- [ ] Fix recipe remover so it removes advancements that reference the recipe.
