### ISSUE TITLE
Rework registry system to use ForgeRegistries constants

### ISSUE THREAD

**Issue by einsteinsci** [einsteinsci/BetterBeginningsReborn#2]
https://github.com/einsteinsci/BetterBeginningsReborn/blob/269574c447555f45a3378b975d38b9af4db51385/src/main/java/net/einsteinsci/betterbeginnings/register/RegisterHelper.java#L55

This function is now private, and may require significant rework to use Forge's new `ForgeRegistries` constants.

**Comment by Daomephsta** [comment]
The intended method of registering registry entries is [registry events](https://mcforge.readthedocs.io/en/latest/concepts/registries/#registering-things). The registry constants are useful for fetching objects from the registry.
