### ISSUE TITLE
Development Status & JEI Support

### ISSUE THREAD

**Issue by Gandalf360one** [einsteinsci/BetterBeginningsReborn#8]
My question is if the mod is still in develop ?
If it is will you reimplement JEI support ?

**Comment by Daomephsta** [comment]
I haven't heard from einsteinsci in years, and I'm no longer interested in maintaining or developing the mod myself. So no, the mod is not in development by either of us. However it is under the GNU GPL v3.0 license, which means others are free to build off what we have made, as long as they follow the terms of the license. A copy of the license can be found in [License.txt](https://github.com/einsteinsci/BetterBeginningsReborn/blob/master/License.txt).

**Comment by einsteinsci** [comment]
Archiving long-abandoned project. If anyone wants to implement this, feel free to clone the project and continue development.
